export enum GameEvent {
    //Common
    NET_CLIENT_CONNECT = "NET_CLIENT_CONNECT",    //网络连接
    NET_CLIENT_NO_CONNECT = "NET_CLIENT_NO_CONNECT",    //网络断开连接
    NET_CLIENT_RE_CONNECT = "NET_CLIENT_RE_CONNECT",    //网络重新连接
    SCENE_PRELOAD = "SCENE_PRELOAD",  //加载下个场景资源
    SCENE_ASYNC_LOAD = "SCENE_ASYNC_LOAD",  //加载当前场景资源
    SCENE_ASYNC_LOAD_COUNT = "SCENE_ASYNC_LOAD_COUNT",  //加载当前场景资源事件
    SENCE_LOADING_ERROR = "SENCE_LOADING_ERROR", //加载当前场景资源错误
    SCENE_ASYNC_LOAD_COUNT_END = "SCENE_ASYNC_LOAD_COUNT_END",  //加载当前场景资源完成事件
    SCENE_LOGIN_OVER_HIDE_LOAD_VIEW = "SCENE_LOGIN_OVER_HIDE_LOAD_VIEW",  //总的登录成功后，关闭当前场景资源完成loading界面
    SCENE_HIDE_LOAD_VIEW = "SCENE_HIDE_LOAD_VIEW",  //关闭当前场景资源完成loading界面
    SCENE_LOAD_VIEW_BEFORE_CLOSE = "SCENE_LOAD_VIEW_CLOSE",  //loading界面关闭前通知
    SCENE_LOAD_VIEW_TIMEOUT = "SCENE_LOAD_VIEW_TIMEOUT",  //loading界面加载超时
    OPEN_WINDOW_PREW = "OPEN_WINDOW_PREW",    //打开窗口前
    OPEN_WINDOW = "OPEN_WINDOW",    //打开窗口
    CLOSE_WINDOW = "CLOSE_WINDOW",    //关闭窗口
    STOP_CLIENT_HEART = "STOP_CLIENT_HEART", //停止主心跳
    EVENT_HEARTBEAT_TIMEOUT = "EVENT_HEARTBEAT_TIMEOUT", //心跳超时
    EVENT_CLIENT_BREAK_NET = "EVENT_CLIENT_BREAK_NET", //主动断网
    EVENT_CLIENT_RECONNECT_NET = "EVENT_CLIENT_RECONNECT_NET",    //断线重新连接

    //game
    EVENT_GAME_LOGIN = "EVENT_GAME_LOGIN",//登录成功
    EVENT_LOGIN_ALL_INFO = "EVENT_LOGIN_ALL_INFO",//登录后需要的信息消息全部完成
    EVENT_GAME_INFO = "EVENT_GAME_INFO",//获取到游戏信息
    EVENT_GAME_RELOGIN = "EVENT_GAME_RELOGIN",//手动重连游戏

    //game
    EVENT_GAME_UPDATE_WALLET = "EVENT_GAME_UPDATE_WALLET",//更新coins
    EVENT_GAME_BET_INFO = "EVENT_GAME_BET_INFO",//更新下注信息
    EVENT_GAME_STATE_INFO = "EVENT_GAME_STATE_INFO",//更新游戏状态
    EVENT_GAME_UPDATE_RECORD = "EVENT_GAME_UPDATE_RECORD",//更新历史记录
    EVENT_GAME_SELF_RECORD = "EVENT_GAME_SELF_RECORD",//更新自己历史记录
    EVENT_GAME_RULE = "EVENT_GAME_RULE",//更新游戏规则信息
    EVENT_GAME_RESULT = "EVENT_GAME_RESULT",//收到游戏结果

}